### ISSUE TITLE
Not possible to play over bluetooth while charging

### ISSUE THREAD

**Issue by NeonNegro** [RetroPie/sixad#13]

**Comment by joolswills** [comment]
Please use the forum for guidance first. https://retropie.org.uk/forum/

**Comment by NeonNegro** [comment]
But it's not possible to charge, what should I do in the forum?

**Comment by joolswills** [comment]
read https://retropie.org.uk/forum/topic/3/read-this-first - provide information about your setup. If we can confirm this is a software bug which can be fixed, we can have a ticket here. But it may well be it isn't something that can be resolved here. I don't even know what controller you have on what system.
